name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Stop server
        run: pm2 stop dialog_server

      - name: Check version
        run: |
          node -v
          npm -v

      - name: Install dependency
        run: npm i

      - name: Start server
        run: pm2 start dialog_server

      - name: Check status
        run: pm2 status
